default_platform(:ios)

platform :ios do

  lane :build do
    setup_ci if ENV['CI']
    match(type: 'appstore')
    increment_build_number(
      xcodeproj: "Tivi.xcodeproj",
      build_number: ENV['TIVI_BUILD_NUMBER']
    )
    build_app(
      scheme: "Tivi",
      buildlog_path: "build/fastlane-buildlog"
    )
  end

  lane :beta do
    build
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

end
