// Copyright 2023, Christopher Banes and the Tivi project contributors
// SPDX-License-Identifier: Apache-2.0

package app.tivi.common.ui.resources

data class TiviStrings(
    val emptyPrompt: String,
    val emptyEmoji: String,
    val headerMore: String,
    val popupSortLastWatched: String,
    val popupSortDateFollowed: String,
    val popupSortAlpha: String,
    val popupSortAirDate: String,
    val genreLabelDrama: String,
    val genreLabelFantasy: String,
    val genreLabelScienceFiction: String,
    val genreLabelAction: String,
    val genreLabelAdventure: String,
    val genreLabelCrime: String,
    val genreLabelThriller: String,
    val genreLabelComedy: String,
    val genreLabelHorror: String,
    val genreLabelMystery: String,
    val discoverTitle: String,
    val cdDiscoverTitle: String,
    val discoverTrendingTitle: String,
    val discoverRecommendedTitle: String,
    val discoverPopularTitle: String,
    val discoverKeepWatchingTitle: String,
    val followingShowsTitle: String,
    val cdFollowingShowsTitle: String,
    val watchedShowsTitle: String,
    val cdWatchedShowsTitle: String,
    val libraryTitle: String,
    val cdLibraryTitle: String,
    val libraryEmptyTitle: String,
    val libraryEmptyPrompt: String,
    val upnextTitle: String,
    val cdUpnextTitle: String,
    val upnextFilterFollowedShowsOnlyTitle: String,
    val upnextEmptyTitle: String,
    val upnextEmptyPrompt: String,
    val login: String,
    val refreshCredentials: String,
    val logout: String,
    val showdetailsNavigationTitle: String,
    val episodeNavigationTitle: String,
    val searchNavigationTitle: String,
    val cdSearchNavigationTitle: String,
    val searchHint: String,
    val searchEmptyTitle: String,
    val searchNoresultsTitle: String,
    val searchNoresultsPrompt: String,
    val accountTitle: String,
    val accountNameUnknown: String,
    val settingsTitle: String,
    val settingsUiCategoryTitle: String,
    val settingsThemeTitle: String,
    val settingsDynamicColorTitle: String,
    val settingsDynamicColorSummary: String,
    val settingsDataSaverTitle: String,
    val settingsDataSaverSummaryOn: String,
    val settingsDataSaverSummarySystem: String,
    val settingsAboutCategoryTitle: String,
    val detailsRelated: String,
    val detailsAbout: String,
    val percentageFormat: (Int) -> String,
    val minutesFormat: (Int) -> String,
    val traktRatingTitle: String,
    val traktRatingText: String,
    val cdTraktRating: String,
    val traktRatingVotes: String,
    val cdEpisodeFirstAired: (String) -> String,
    val networkTitle: String,
    val certificateTitle: String,
    val runtimeTitle: String,
    val ratingContentDescriptionFormat: (Int) -> String,
    val networkContentDescriptionFormat: (String) -> String,
    val certificateContentDescriptionFormat: (String) -> String,
    val detailsViewStats: String,
    val detailsNextEpisodeToWatch: String,
    val followShowAdd: String,
    val followShowRemove: String,
    val cdFollowShowAdd: String,
    val cdFollowShowRemove: String,
    val followShowsAdd: String,
    val followShowsRemove: String,
    val episodeWatches: String,
    val episodeMarkWatched: String,
    val episodeAddWatch: String,
    val firstAired: (String) -> String,
    val seasonSummaryToWatch: (Int) -> String,
    val seasonSummaryToAir: (Int) -> String,
    val seasonSummaryWatched: (Int) -> String,
    val popupSeasonWatchNow: String,
    val popupSeasonWatchAirDate: String,
    val popupSeasonMarkWatchedAll: String,
    val popupSeasonMarkWatchedAired: String,
    val popupSeasonMarkAllUnwatched: String,
    val popupSeasonFollow: String,
    val popupSeasonIgnore: String,
    val popupSeasonIgnorePrevious: String,
    val showDetailsSeasons: String,
    val viewPrivacyPolicy: String,
    val notKnownTitle: String,
    val libraryLastWatched: (String) -> String,
    val nextPrefix: (String) -> String,
    val filterShows: (Int) -> String,
    val selectionTitle: (Int) -> String,
    val episodeNumber: (Int) -> String,
    val seasonEpisodeNumber: (Int, Int) -> String,
    val seasonTitleFallback: (Int) -> String,
    val episodeTitleFallback: (Int) -> String,
    val followedWatchStatsComplete: String,
    val menuRefresh: String,
    val privacyPolicyUrl: String,
    val settingsAppVersion: String,
    val settingsAppVersionSummary: (String, Int) -> String,
    val settingsOpenSource: String,
    val settingsOpenSourceSummary: String,
    val errorGeneric: String,
    val statusTitle: String,
    val statusEnded: String,
    val statusActive: String,
    val statusInProduction: String,
    val statusPlanned: String,
    val airsTitle: String,
    val airsText: (String, String) -> String,
    val episodeRemoveWatchesDialogTitle: String,
    val episodeRemoveWatchesDialogMessage: String,
    val episodeRemoveWatchesDialogConfirm: String,
    val dialogDismiss: String,
    val cdShowPoster: String,
    val cdShowPosterImage: (String) -> String,
    val cdProfilePic: (String) -> String,
    val cdClearText: String,
    val cdRefresh: String,
    val cdSortList: String,
    val cdDelete: String,
    val cdNetworkLogo: String,
    val cdUserProfile: String,
    val cdNavigateUp: String,
    val cdOpenOverflow: String,
    val cdClose: String,
    val cdEpisodeSyncing: String,
    val cdEpisodeWatched: String,
    val cdEpisodeDeleted: String,
    val episodeTrackPrompt: String,
    val episodeTrackNow: String,
    val episodeTrackSetFirstAired: String,
    val buttonConfirm: String,
    val timeLabel: String,
    val episodeWatchTimeTitle: String,
    val dateLabel: String,
    val episodeWatchDateTitle: String,
    val headerShowCount: (quantity: Int) -> String,
    val headerShowCountFiltered: (quantity: Int) -> String,
    val followedWatchStatsToWatch: (quantity: Int) -> String,
)

object Locales {
    const val EN = "en"
}

expect fun String.fmt(vararg args: Any?): String
