platform :ios, '15.2'

target 'Tivi' do
  use_frameworks!
  
  pod 'AppAuth', '1.7.5'
  pod 'FirebaseAnalytics', '10.29.0'
  pod 'FirebaseCrashlytics', '10.29.0'
  pod 'PurchasesHybridCommon', '11.1.1'
  pod 'PurchasesHybridCommonUI', '11.1.1'
end
