default_platform(:ios)

platform :ios do

  before_all do |lane|
    cleanup_ci_keychain if is_ci
  end

  after_all do |lane|
    cleanup_ci_keychain if is_ci
  end

  error do |lane, exception|
    cleanup_ci_keychain if is_ci
  end

  lane :certs do |options|
    app_store_connect_api_key(
      key_id: ENV['API_KEY_ID'],
      issuer_id: ENV['ISSUER_KEY_ID'],
      key_content: ENV['API_KEY_CONTENTS'],
      is_key_content_base64: true
    )

    match(
      app_identifier: ["app.tivi.client", "app.tivi.qa"],
      type: options[:type] || "development"
    )
  end

  lane :lint do
    swiftlint(
      mode: :lint,
      path: "ios-app/Tivi",
      strict: true,
      raise_if_swiftlint_error: true
    )
  end

  private_lane :build_tivi do |options|
    setup_ci if is_ci

    certs(type: 'appstore') if ENV['MATCH_PASSWORD']

    increment_build_number(
      xcodeproj: "ios-app/Tivi/Tivi.xcodeproj",
      build_number: ENV['TIVI_BUILD_NUMBER']
    ) if ENV['TIVI_BUILD_NUMBER']

    # If match hasn't been setup, skip all code signing and packaging
    skip_packaging = ENV['MATCH_PASSWORD'].nil?

    build_app(
      project: "ios-app/Tivi/Tivi.xcodeproj",
      scheme: options[:scheme],
      buildlog_path: "build/fastlane-buildlog",
      skip_package_ipa: skip_packaging,
      skip_codesigning: skip_packaging
    )
  end

  lane :build_qa do
    build_tivi(scheme: "Tivi QA")
  end

  lane :build_prod do
    build_tivi(scheme: "Tivi Prod")
  end

  lane :build_all do
    build_qa
    build_prod
  end

  lane :publish_qa do
    app_store_connect_api_key(
      key_id: ENV['API_KEY_ID'],
      issuer_id: ENV['ISSUER_KEY_ID'],
      key_content: ENV['API_KEY_CONTENTS'],
      is_key_content_base64: true
    )

    upload_to_testflight(app_identifier: "app.tivi.qa")
  end

  lane :publish_prod do
    app_store_connect_api_key(
      key_id: ENV['API_KEY_ID'],
      issuer_id: ENV['ISSUER_KEY_ID'],
      key_content: ENV['API_KEY_CONTENTS'],
      is_key_content_base64: true
    )

    upload_to_testflight(app_identifier: "app.tivi.client")
  end

end

def cleanup_ci_keychain(name = "fastlane_tmp_keychain")
  if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
    puts "CI keychain exists. Deleting it and restoring the default keychain"
    delete_keychain(name: name)
    sh("security default-keychain -s ~/Library/Keychains/login.keychain-db")
  end
end
